### ISSUE TITLE
Organic Group subscribe message

### ISSUE THREAD

**Issue by sag13684** [sag13684/drupal-starter#1]
Whenever a registered user will visit the group, it should offer to subscribe to that user by greeting them with their name: “Hi Foo, click here if you would like to subscribe to this group called Bar”. To test the greeting message, follow the steps below:
- Install the site locally using the repo's README file.
- Login to the site using admin credentials or To get a one-time login link for the admin user, use the command `drush uli`. Visit the one-time login link to get logged in as an admin user.
- Create a group node by going to node/add/group, fill-up the form fields, and hit the Save button.
- In a different browser tab, Login to the site using authenticated user credentials. Visit the group node created in the earlier step.
- Verify the group join link says: "Hi [username], click here if you would like to subscribe to this group called [group-title]"
- Example group node with custom group link message:

![image](https://user-images.githubusercontent.com/878728/87529009-fb892d80-c6ab-11ea-8844-776950517021.png)

Formatter Class: [GizraGroupSubscribeFormatter](https://github.com/sag13684/drupal-starter/blob/master/web/modules/custom/gizra_custom/src/Plugin/Field/FieldFormatter/GizraGroupSubscribeFormatter.php)
Test Class: [GizraCustomWebDriverTest](https://github.com/sag13684/drupal-starter/blob/master/web/modules/custom/gizra_custom/tests/src/ExistingSite/GizraCustomWebDriverTest.php)

Run Test: `ddev phpunit -vvv --bootstrap=vendor/weitzman/drupal-test-traits/src/bootstrap-fast.php web/modules/custom/gizra_custom/`

**Comment by amitaibu** [comment]
Thanks.

1. Is there a way of making the formatter's code shorter (seems like a lot of duplication)?
1. Yout tests seems to be using the `ExistingSiteWebDriverTestBase`, is there a reason for that instead of using `ExistingSite`? In that case I believe `ddev phpunit` will not work without further commands/ setup?

**Comment by sag13684** [comment]
@amitaibu Thank you for your review. I had made changes to both the classes as per your suggestions in points 1 and 2.
